// <auto-generated />
using System;
using BlogAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BlogAPI.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Perex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Content = "Clean Architecture is a software design philosophy...",
                            Perex = "A brief overview of the principles and benefits of Clean Architecture.",
                            Timestamp = new DateTime(2025, 7, 22, 14, 59, 40, 94, DateTimeKind.Utc).AddTicks(5070),
                            Title = "Introduction to Clean Architecture",
                            UserId = 1
                        },
                        new
                        {
                            Id = 102,
                            Content = "ASP.NET Core is a cross-platform, high-performance framework...",
                            Perex = "A guide for beginners to set up their first ASP.NET Core project.",
                            Timestamp = new DateTime(2025, 7, 24, 14, 59, 40, 94, DateTimeKind.Utc).AddTicks(5080),
                            Title = "Getting Started with ASP.NET Core",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BlogAPI.Models.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            ArticleId = 101,
                            Author = "",
                            Content = "Great article, very insightful!",
                            Timestamp = new DateTime(2025, 7, 23, 14, 59, 40, 94, DateTimeKind.Utc).AddTicks(5090),
                            UserId = 2
                        },
                        new
                        {
                            Id = 1002,
                            ArticleId = 102,
                            Author = "",
                            Content = "Thanks for the guide, it helped me a lot.",
                            Timestamp = new DateTime(2025, 7, 25, 14, 59, 40, 94, DateTimeKind.Utc).AddTicks(5090),
                            UserId = 1
                        },
                        new
                        {
                            Id = 1003,
                            ArticleId = 101,
                            Author = "",
                            Content = "I have a question about the dependency rule.",
                            Timestamp = new DateTime(2025, 7, 23, 16, 59, 40, 94, DateTimeKind.Utc).AddTicks(5100),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BlogAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "john.doe@example.com",
                            PasswordHash = "$2a$11$4fX3ebecDhfHd4XbO4plvuHDvHONNdceBSvbm10PwkY9pCkF8Y8fq",
                            Username = "john.doe"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "jane.smith@example.com",
                            PasswordHash = "$2a$11$FgWJeYpAgR./cUJj/5PW6e.4cOliTv.eMBsATeewXUf8RnXEoUd/.",
                            Username = "jane.smith"
                        });
                });

            modelBuilder.Entity("BlogAPI.Models.Article", b =>
                {
                    b.HasOne("BlogAPI.Models.User", "User")
                        .WithMany("Articles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlogAPI.Models.Comments", b =>
                {
                    b.HasOne("BlogAPI.Models.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogAPI.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlogAPI.Models.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("BlogAPI.Models.User", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
